//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baocao_chuyende.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationShop
    {
        public int id { get; set; }
        public string address { get; set; }
        public string zalo { get; set; }
        public string hotline { get; set; }
        public string wholesale { get; set; }
    }
}
