//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baocao_chuyende.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductDetails = new HashSet<ProductDetail>();
        }
    
        public int id { get; set; }
        public string nameProduct { get; set; }
        public Nullable<int> idCategory { get; set; }
        public Nullable<int> idBrands { get; set; }
        public Nullable<int> idType { get; set; }
        [AllowHtml]
        public string description { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> saleoff { get; set; }
        public Nullable<int> inventory { get; set; }
        public string sizechart { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
    }
}
