//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baocao_chuyende.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int id { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<int> idColor { get; set; }
        public Nullable<int> idSize { get; set; }
        public string image { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Size Size { get; set; }
        public virtual Product Product { get; set; }
    }
}
